# generated by datamodel-codegen:
#   filename:  ItemSetsRoot.json
#   timestamp: 2025-06-08T12:31:43+00:00

from __future__ import annotations

from typing import List, Optional

from msgspec import Struct, field


class Value(Struct, frozen=True, kw_only=True):
    rid: int


class Effect(Struct, frozen=True, kw_only=True):
    values: List[Value]


class ZoneDescr(Struct, frozen=True, kw_only=True):
    cellIds: List
    shape: int
    param1: int
    param2: int
    damageDecreaseStepPercent: int
    maxDamageDecreaseApplyCount: int
    isStopAtTarget: int


class ItemsetsrootItem(Struct, frozen=True, kw_only=True):
    id: Optional[int] = None
    items: Optional[List[int]] = None
    nameId: Optional[int] = None
    bonusIsSecret: Optional[int] = None
    effects: Optional[List[Effect]] = None
    m_flags: Optional[int] = None
    effectUid: Optional[int] = None
    baseEffectId: Optional[int] = None
    effectId: Optional[int] = field(default=None, name="actionId")
    order: Optional[int] = None
    targetId: Optional[int] = None
    targetMask: Optional[str] = None
    duration: Optional[int] = None
    random: Optional[float] = None
    group: Optional[int] = None
    modificator: Optional[int] = None
    dispellable: Optional[int] = None
    delay: Optional[int] = None
    triggers: Optional[str] = None
    effectElement: Optional[int] = None
    spellId: Optional[int] = None
    effectTriggerDuration: Optional[int] = None
    zoneDescr: Optional[ZoneDescr] = None
    value: Optional[int] = None
    diceNum: Optional[int] = None
    diceSide: Optional[int] = None
    displayZero: Optional[int] = None


Itemsetsroot = List[ItemsetsrootItem]
