# generated by datamodel-codegen:
#   filename:  SpellLevelsRoot.json
#   timestamp: 2024-11-22T22:22:16+00:00

from __future__ import annotations

from msgspec import Struct, field

from DBDofusUnity.dofus_unity_reader.models.datas.zone_descr import ZoneDescr


class Effect(Struct, frozen=True, kw_only=True):
    m_flags: int
    effectUid: int
    baseEffectId: int
    effectId: int = field(name="actionId")
    order: int
    targetId: int
    targetMask: str
    duration: int
    random: float
    group: int
    modificator: int
    dispellable: int
    delay: int
    triggers: str
    effectElement: int
    spellId: int
    effectTriggerDuration: int
    zoneDescr: ZoneDescr
    value: int
    diceNum: int
    diceSide: int
    displayZero: int

    def __hash__(self):
        return self.effectUid.__hash__()


class PreviewZone(Struct, frozen=True, kw_only=True):
    id: int
    displayZoneDescr: ZoneDescr
    isPreviewZoneHidden: int
    casterMask: str
    activationZoneDescr: ZoneDescr
    activationMask: str

    def __hash__(self):
        return self.id.__hash__()


class SpellLevelsRootItem(Struct, frozen=True, kw_only=True):
    m_flags: int
    id: int
    spellId: int
    grade: int
    spellBreed: int
    apCost: int
    minRange: int
    range: int
    criticalHitProbability: int
    maxStack: int
    maxCastPerTurn: int
    maxCastPerTarget: int
    minCastInterval: int
    initialCooldown: int
    globalCooldown: int
    minPlayerLevel: int
    statesCriterion: str
    effects: list[Effect]
    criticalEffect: list[Effect]
    previewZones: list[PreviewZone]

    def __hash__(self):
        return self.id.__hash__()


SpellLevelsRoot = list[SpellLevelsRootItem]
